# Primary DataSource (H2 - db1)
spring.datasource.primary.jdbc-url=jdbc:h2:mem:db1
spring.datasource.primary.username=sa
spring.datasource.primary.password=
spring.datasource.primary.driver-class-name=org.h2.Driver

# Secondary DataSource (H2 - db2)
spring.datasource.secondary.jdbc-url=jdbc:h2:mem:db2
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=
spring.datasource.secondary.driver-class-name=org.h2.Driver

# H2 Console (enable to view both DBs in browser at /h2-console)
spring.h2.console.enabled=true
